### ISSUE TITLE
fixed filename date offset for attachments

### ISSUE THREAD

**Issue by chrismazanec** [ahochsteger/gmail-processor#135]
**Is your feature request related to a problem? Please describe.**
Companies email me PDF invoices on a monthly basis. These are usually sent later than the invoice issue date. Currently I need to rename the files manually so the file name matches the invoice issue date.

**Describe the solution you'd like**
I want files to be saved with the name `yyyy-MM-dd_invoice.pdf`, offsetting the `dd` part by e.g. -2 days (fixed number of days), so when the mail arrives on `2023-09-27`, the file would be saved as `2023-09-25_invoice.pdf`.

**Describe alternatives you've considered**
I have this solution implemented in my fork of old `gmail2gdrive`, simply adding one more parameter `dateOffset`
https://github.com/ahochsteger/gmail-processor/compare/main...chrismazanec:gmail2gdrive:master#diff-2150ba4293f0c9b92056a7b06af5d57993334974e93150f0a86eecac4b8a6405R89

```
  // Adjust message date by optional offset in days
  if (typeof rule.dateOffset !== 'undefined') {
    messageDate.setDate( messageDate.getDate() - rule.dateOffset );
  }
```

**Comment by ahochsteger** [comment]
@chrismazanec I understand that you need this feature in order to migrate to Gmail Processor.
I'm not sure, if an offset would reliably work for all users, taking holidays and weekends into account.
Therefore I'd like to know a bit more about your use case and esp. if it would be possible to extract the correct invoice date from the email message text itself using a regex?

**Comment by chrismazanec** [comment]
yes, I'd like to migrate to Gmail Processor, my coding skills are limited.

the offset solution is not perfect but works better than none. unfortunately, the invoice date is only available inside the PDF itself. a typical example is a PDF invoice from Google Workspace (gsuite), invoice comes on the 1st of each month, the invoice issue date being the last date of the preceding month. I have more use cases like this, some of the emails come in the middle of the month.

**Comment by ahochsteger** [comment]
@chrismazanec, would it be possible for you to test the PR #143 which implements the feature you requested?
You can use the script ID `1yhOQyl_xWtnGJn_bzlL7oA4d_q5KoMyZyWIqXDJX1SY7bi22_lpjMiQK` and version `124` of the Gmail Processor Lib in Google Apps Script that points to a development snapshot containing these changes.
When you confirm that it's working, I'll merge the PR and create a new release.

**Comment by chrismazanec** [comment]
finally got to testing this, works like a charm, thank you for your work!  🙏
