### ISSUE TITLE
Error when switching from MARK_MESSAGE_READ to ADD_THREAD_LABEL in GmailProcessorLib

### ISSUE THREAD

**Issue by SlashGordon** [ahochsteger/gmail-processor#150]
# Description
**Issue**
I encountered an error when attempting to switch from `MARK_MESSAGE_READ` to `ADD_THREAD_LABEL` in my GmailProcessorLib configuration. The error message I received is as follows:

```
Error: Error "Exception: Invalid argument: name" during execution of action thread.addLabel using args {"label":"some-label"}!
handleActionResult	@ GmailProcessorLib.gs:3186
(Anonym)	@ GmailProcessorLib.gs:3207
(Anonym)	@ GmailProcessorLib.gs:3196
executeActions	@ GmailProcessorLib.gs:3192
processEntity	@ GmailProcessorLib.gs:3754
processConfigs	@ GmailProcessorLib.gs:3736
run	@ GmailProcessorLib.gs:3370
runWithJson	@ GmailProcessorLib.gs:3390
```

**Reproduction Steps**
1. Modify the `config` variable to use `ADD_THREAD_LABEL` for the `markProcessedMethod` as follows:
   ```javascript
   var config = {
     description: "Save pdf to gdrive",
     settings: {
       markProcessedMethod: GmailProcessorLib.MarkProcessedMethod.ADD_THREAD_LABEL,
       markProcessedLabel: "some-label",
     },
     global: {},
     threads: [
       {
         attachments: [
           {
             match: {
               contentType: "application/pdf",
             },
             actions: [
               {
                 name: "attachment.store",
                 args: {
                   conflictStrategy: GmailProcessorLib.ConflictStrategy.BACKUP,
                   location: "/mailattachments/${message.date:format:yyyy-MM-dd}_${attachment.name}"
                 }
               }
             ]
           }
         ]
       }
     ]
   }
   ```

2. Run the code using the `run` function.

**Expected Behavior**
I expected that when switching from `MARK_MESSAGE_READ` to `ADD_THREAD_LABEL`, the GmailProcessorLib would add the specified label to the thread, as configured.

**Actual Behavior**
Instead, I received an error as described above.

# Environment
- GmailProcessorLib Version: 14

Thank you for your assistance in resolving this issue.

**Comment by ahochsteger** [comment]
@SlashGordon would it be possible for you to put the full effective config here - it is typically logged at the beginning of the log stream and starting with this entry:
```
DEBUG: ProcessingContext: {
```

**Comment by SlashGordon** [comment]
@ahochsteger Kudos for the lightning-fast response! Here's the coveted config straight from the logs::`ProcessingContext: {
  "config": {
    "description": "Save pdf to gdrive",
    "global": {
      "attachment": {
        "actions": [],
        "description": "",
        "match": {
          "contentType": ".*",
          "includeAttachments": true,
          "includeInlineImages": true,
          "largerThan": -1,
          "name": "(.*)",
          "smallerThan": -1
        },
        "name": ""
      },
      "message": {
        "actions": [],
        "description": "",
        "attachments": [],
        "match": {
          "body": ".*",
          "from": ".*",
          "is": [],
          "newerThan": "",
          "olderThan": "",
          "plainBody": ".*",
          "subject": ".*",
          "to": ".*"
        },
        "name": ""
      },
      "thread": {
        "actions": [
          {
            "args": {
              "label": "some-label"
            },
            "description": "",
            "name": "thread.addLabel",
            "processingStage": "post-main"
          }
        ],
        "description": "",
        "messages": [],
        "attachments": [],
        "match": {
          "firstMessageSubject": ".*",
          "labels": ".*",
          "maxMessageCount": -1,
          "minMessageCount": 1,
          "query": "has:attachment -in:trash -in:drafts -in:spam newer_than:1d -label:some-label"
        },
        "name": ""
      },
      "variables": []
    },
    "threads": [
      {
        "actions": [],
        "description": "",
        "messages": [
          {
            "actions": [],
            "description": "",
            "attachments": [
              {
                "actions": [
                  {
                    "args": {
                      "conflictStrategy": "backup",
                      "location": "/mailattachments/${message.date:format:yyyyMMdd}_${attachment.name}"
                    },
                    "description": "",
                    "name": "attachment.store",
                    "processingStage": "post-main"
                  }
                ],
                "description": "",
                "match": {
                  "contentType": "application/pdf",
                  "includeAttachments": true,
                  "includeInlineImages": true,
                  "largerThan": -1,
                  "name": "(.*)",
                  "smallerThan": -1
                },
                "name": ""
              }
            ],
            "match": {
              "body": ".*",
              "from": ".*",
              "is": [],
              "newerThan": "",
              "olderThan": "",
              "plainBody": ".*",
              "subject": ".*",
              "to": ".*"
            },
            "name": ""
          }
        ],
        "attachments": [],
        "match": {
          "firstMessageSubject": ".*",
          "labels": ".*",
          "maxMessageCount": -1,
          "minMessageCount": 1,
          "query": "has:attachment -in:trash -in:drafts -in:spam newer_than:1d"
        },
        "name": ""
      }
    ],
    "settings": {
      "logSheetLocation": "",
      "maxBatchSize": 10,
      "maxRuntime": 280,
      "markProcessedLabel": "some-label",
      "markProcessedMethod": "add-label",
      "sleepTimeThreads": 100,
      "sleepTimeMessages": 0,
      "sleepTimeAttachments": 0,
      "timezone": "default"
    }
  }
} debug` 

Your quick action is much appreciated. Thanks for being awesome!

**Comment by ahochsteger** [comment]
Unfortunately there was still one more issue with labels in v2.3.1 so another fix will be released shortly.
