### ISSUE TITLE
Getting started | Syntax error: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by sitebroke** [ahochsteger/gmail-processor#161]
### Describe the bug

Following the getting started guide, : 
https://ahochsteger.github.io/gmail-processor/docs/getting-started/

Step 6. Replace the contents of the initially created file Code.gs with the code from the [Getting Started Example](https://ahochsteger.github.io/gmail-processor/docs/examples/gettingStarted) and save the changes.

When I do so I get : Syntax error: SyntaxError: Unexpected token ':' line: 2 file: Code.gs

### To Reproduce

Run through your getting started guide.

### Logs / Screenshots

![image](https://github.com/ahochsteger/gmail-processor/assets/148437605/a9d07351-d66e-4429-ba13-9a95eb4de197)

### Additional context

Affected version of gmail-processor:
 17

**Comment by ahochsteger** [comment]
@sitebroke thanks for spotting the mistake in the documentation, there is some code missing as it just shows the configuration but not the code to execute the configuration.
You can use it this way:
```javascript
var config = ... // Put the getting started configuration here

function run() {
  // NOTE: Switch to "safe-mode" after testing the config
  GmailProcessorLib.run(config, "dry-run")
}
```

**Comment by ahochsteger** [comment]
FYI: The [Getting Started Guide](https://ahochsteger.github.io/gmail-processor/docs/getting-started) is now fixed.
