### ISSUE TITLE
images missing in the saved PDF file with function "save the thread as a PDF file"

### ISSUE THREAD

**Issue by zzpy20** [ahochsteger/gmail-processor#26]
Hi Andreas, thanks for the great work. Not sure if it's only me or an existing issue. The function 'save email thread as PDF file' doesn't seem to include the images in the email body. In my case, all the PDF files saved have empty areas where the images were supposed to fill. Everything works brilliantly except the images were not on the PDF file. 

I am not a programmer, so hope anyone can help. 

Regards
Alan

**Comment by ahochsteger** [comment]
@ottonet, do you know if the PDF functionality you originally implemented is capable of including embedded images in the emails?
From looking at the code it fully depends on the API function "message.getBody()" but I don't know if it is able to handle embedded images.

**Comment by ahochsteger** [comment]
Found a possible solution using this library:
https://github.com/pixelcog/gmail-to-pdf

**Comment by ahochsteger** [comment]
@zzpy20, @chrismazanec it would be great to get some feedback if it works for you as intended.
See this resources on how to use the new actions `thread.exportAsPdf` and `message.exportAsPdf` (*.storePDF is now deprecated):
* https://ahochsteger.github.io/gmail-processor/docs/reference/actions#messageexportaspdf
* https://ahochsteger.github.io/gmail-processor/docs/reference/actions#threadexportaspdf
* https://github.com/ahochsteger/gmail-processor/blob/main/src/gas/examples/pr-291.js
