### ISSUE TITLE
custom placeholder from PDF OCR

### ISSUE THREAD

**Issue by chrismazanec** [ahochsteger/gmail-processor#260]
**Is your feature request related to a problem? Please describe.**
when receiving PDF invoices in the attachment, they contain an invoice date. the invoice date often doesn't not match the message date - i.e. the invoice is sent with a delay - a few days later after the purchase.

**Describe the solution you'd like**
I'd like to process the attachment using OCR and extract the date from the document, and later use it as a placeholder for filename - save the filename with the date extracted from inside the document.

**Describe alternatives you've considered**
using `offset-format` feature, which works but is not 100% reliable - email is sent at different dates (+- 1-2 days) https://github.com/ahochsteger/gmail-processor/pull/143

**Additional context**
something like this; https://www.labnol.org/extract-text-from-pdf-220422

thank you for considering and for your great work! 🙏

**Comment by ahochsteger** [comment]
@chrismazanec the PR #319 implements what you need using a new action `attachment.extractText`.
It would be great if you could give it a try and give me some feedback.
You can use the library ID `1yhOQyl_xWtnGJn_bzlL7oA4d_q5KoMyZyWIqXDJX1SY7bi22_lpjMiQK` for testing that has the branch of the PR deployed.

**Comment by chrismazanec** [comment]
thank you for your work @ahochsteger 🙏

my date is in format `29.03.2024` (MM.DD.YYYY). this is what I ended up with.
```
              "actions": [
                {
                  "name": "attachment.extractText",
                  "args": {
                   "extract": "Delivery date:\\s*(?<deliveryDay>[0-9]{2}).(?<deliveryMonth>[0-9]{2}).(?<deliveryYear>[0-9]{4})"
                  },
                  "processingStage": "pre-main"
                },
                {
                  "name": "attachment.store",
                  "args": {
                   "location": "test/${attachment.extracted.match.deliveryYear}-${attachment.extracted.match.deliveryMonth}-${attachment.extracted.match.deliveryDay}_${attachment.name}",
                    "conflictStrategy": "backup"
                  }
                }
              ]
```
- this works great, but I wonder if there's a better way. can I handle `29.03.2024` as a date? I tried the code below but failed with an error
```
              "actions": [
                {
                  "name": "attachment.extractText",
                  "args": {
                   "extract": "Delivery date:\\s*(?<deliveryDate>[0-9]{2}.[0-9]{2}).[0-9]{4})"
                  },
                  "processingStage": "pre-main"
                },
                {
                  "name": "attachment.store",
                  "args": {
                   "location": "test/${attachment.extracted.match.deliveryDate:date::yyyy-MM-DD}_${attachment.name}",
                    "conflictStrategy": "backup"
                  }
                }
              ]
```

**Comment by ahochsteger** [comment]
@chrismazanec I've created a separate Issue to track your use case of parsing dates with a custom date format:
https://github.com/ahochsteger/gmail-processor/issues/345
