### ISSUE TITLE
Issue with forwarding email

### ISSUE THREAD

**Issue by ptorner** [ahochsteger/gmail-processor#261]
### Describe the bug

Have a simple configuration when I want a email with a label `test-automation` to be forwarded using the `message.forward`

### To Reproduce

```
var config = {
  "settings": {
    "markProcessedMethod": "add-label",
    "markProcessedLabel": "gmail2gdrive/client-test",
    "timezone": "GMT"
  },
  "threads": [
    {
      "actions": [
        {
          "name": "message.forward",
          "args": {
            "to": "info@example.org"
          }
        }
      ],
      "match": {
        "query": "label:test-automation"
      }
    }
  ]
}

function run() {
  // NOTE: Switch to "safe-mode" after testing the config
  GmailProcessorLib.run(config, "safe-mode")
}

```
### Expected behavior

The function will crash and send error message below.

### Logs / Screenshots

```
10:20:42 AM	Error	
Error: Error in action 'message.forward': TypeError: Cannot read properties of undefined (reading 'object')
Processing Trace:
{
  "traces": {
    "thread": {
      "configIndex": 0,
      "index": 0,
      "match": {
        "firstMessageSubject": ".*",
        "labels": ".*",
        "maxMessageCount": -1,
        "minMessageCount": 1,
        "query": "label:test-automation"
      },
      "object": {
        "id": "18d0216xxxxxxxxxx",
        "firstMessageSubject": "test email with attachment",
        "lastMessageDate": "2024-01-13T09:09:58.000Z",
        "messageCount": 1,
        "permalink": "https://mail.google.com/mail?extsrc=sync&client=docs&plid=XXXXXXXXXXXXXXXXXXX"
      }
    }
  },
  "action": {
    "description": "",
    "name": "message.forward",
    "processingStage": "post-main",
    "args": {
      "to": "info@example.org"
    }
  },
  "data": {
    "timer.startTime": "2024-01-13T09:20:42.015Z",
    "thread.index": 0,
    "threadConfig.index": 0,
    "thread.matched": true
  },
  "error": {
    "message": "Cannot read properties of undefined (reading 'object')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'object')\n    at forward (GmailProcessorLib:372:79)\n    at descriptor.value (GmailProcessorLib:3941:35)\n    at ActionRegistry.executeAction (GmailProcessorLib:218:20)\n    at GmailProcessorLib:3299:60\n    at Array.forEach (<anonymous>)\n    at GmailProcessorLib:3296:18\n    at Array.forEach (<anonymous>)\n    at ThreadProcessor.executeActions (GmailProcessorLib:3292:28)\n    at ThreadProcessor.processEntity (GmailProcessorLib:3866:23)\n    at ThreadProcessor.processConfigs (GmailProcessorLib:3848:31)"
  }
}
handleActionResult	@ GmailProcessorLib.gs:3286
(anonymous)	@ GmailProcessorLib.gs:3307
(anonymous)	@ GmailProcessorLib.gs:3296
executeActions	@ GmailProcessorLib.gs:3292
processEntity	@ GmailProcessorLib.gs:3866
processConfigs	@ GmailProcessorLib.gs:3848
run	@ GmailProcessorLib.gs:3480
runWithJson	@ GmailProcessorLib.gs:3500
```

### Additional context

Affected version of gmail-processor: 19

**Comment by ptorner** [comment]
added execution log from dry-run:
--------

9:32:12 AM	Notice	Execution started
9:32:12 AM	Info	[2024-01-19T08:32:12.749Z] INFO: Processing of GmailProcessor config started ...
9:32:12 AM	Info	[2024-01-19T08:32:12.751Z] INFO: Setting up action registry ...
9:32:12 AM	Info	[2024-01-19T08:32:12.816Z] DEBUG: ProcessingContext: {
  "config": {
    "description": "",
    "global": {
      "attachment": {
        "actions": [],
        "description": "",
        "match": {
          "contentType": ".*",
          "includeAttachments": true,
          "includeInlineImages": true,
          "largerThan": -1,
          "name": "(.*)",
          "smallerThan": -1
        },
        "name": ""
      },
      "message": {
        "actions": [],
        "description": "",
        "attachments": [],
        "match": {
          "body": ".*",
          "from": ".*",
          "is": [],
          "newerThan": "",
          "olderThan": "",
          "plainBody": ".*",
          "subject": ".*",
          "to": ".*"
        },
        "name": ""
      },
      "thread": {
        "actions": [
          {
            "description": "",
            "name": "thread.addLabel",
            "processingStage": "post-main",
            "args": {
              "name": "gmail2gdrive/client-test"
            }
          }
        ],
        "description": "",
        "messages": [],
        "attachments": [],
        "match": {
          "firstMessageSubject": ".*",
          "labels": ".*",
          "maxMessageCount": -1,
          "minMessageCount": 1,
          "query": "has:attachment -in:trash -in:drafts -in:spam newer_than:1d -label:gmail2gdrive/client-test"
        },
        "name": ""
      },
      "variables": []
    },
    "threads": [
      {
        "actions": [
          {
            "description": "",
            "name": "message.forward",
            "processingStage": "post-main",
            "args": {
              "to": "info@example.org"
            }
          }
        ],
        "description": "",
        "messages": [],
        "attachments": [],
        "match": {
          "firstMessageSubject": ".*",
          "labels": ".*",
          "maxMessageCount": -1,
          "minMessageCount": 1,
          "query": "label:test-automation"
        },
        "name": ""
      }
    ],
    "settings": {
      "logSheetLocation": "",
      "maxBatchSize": 10,
      "maxRuntime": 280,
      "markProcessedLabel": "gmail2gdrive/client-test",
      "markProcessedMethod": "add-label",
      "sleepTimeThreads": 100,
      "sleepTimeMessages": 0,
      "sleepTimeAttachments": 0,
      "timezone": "GMT"
    }
  }
} debug
9:32:12 AM	Info	[2024-01-19T08:32:12.818Z] INFO: Processing of thread config index '0' started ...
9:32:12 AM	Info	[2024-01-19T08:32:12.820Z] DEBUG: Built GMail search query: has:attachment -in:trash -in:drafts -in:spam newer_than:1d -label:gmail2gdrive/client-test label:test-automation
9:32:12 AM	Info	[2024-01-19T08:32:12.821Z] INFO: GMail search query: has:attachment -in:trash -in:drafts -in:spam newer_than:1d -label:gmail2gdrive/client-test label:test-automation
9:32:13 AM	Info	[2024-01-19T08:32:13.015Z] INFO: -> got 1 threads
9:32:13 AM	Info	[2024-01-19T08:32:13.313Z] DEBUG: Testing regex matches for key prefix thread ...
9:32:13 AM	Info	[2024-01-19T08:32:13.314Z] DEBUG: Testing regex match for firstMessageSubject ...
9:32:13 AM	Info	[2024-01-19T08:32:13.316Z] DEBUG: ... matches
9:32:13 AM	Info	[2024-01-19T08:32:13.317Z] DEBUG: Testing regex match for labels ...
9:32:13 AM	Info	[2024-01-19T08:32:13.319Z] DEBUG: ... matches
9:32:13 AM	Info	[2024-01-19T08:32:13.320Z] DEBUG: ... result for thread.matched: true
9:32:13 AM	Info	[2024-01-19T08:32:13.322Z] INFO: Processing of thread id 18d20d78b7e328b6 (subject:'test2') started ...
9:32:13 AM	Info	[2024-01-19T08:32:13.323Z] INFO: Executing action 'message.forward' with args: {"to":"info@example.org"}
9:32:13 AM	Info	[2024-01-19T08:32:13.324Z] INFO: Skipped calling method 'forward' (runMode:dry-run)
9:32:13 AM	Info	[2024-01-19T08:32:13.325Z] INFO: Action result: {"ok":true}
9:32:13 AM	Info	[2024-01-19T08:32:13.326Z] INFO: Executing action 'thread.addLabel' with args: {"name":"gmail2gdrive/client-test"}
9:32:13 AM	Info	[2024-01-19T08:32:13.327Z] INFO: Skipped calling method 'addLabel' (runMode:dry-run)
9:32:13 AM	Info	[2024-01-19T08:32:13.328Z] INFO: Action result: {"ok":true}
9:32:13 AM	Info	[2024-01-19T08:32:13.329Z] INFO: Processing of thread id 18d20d78b7e328b6 finished.
9:32:13 AM	Info	[2024-01-19T08:32:13.330Z] INFO: Processing of thread config index '0' finished.
9:32:13 AM	Info	[2024-01-19T08:32:13.331Z] INFO: Processing of GmailProcessor config finished.
9:32:13 AM	Info	[2024-01-19T08:32:13.332Z] INFO: Processing summary:
9:32:13 AM	Info	[2024-01-19T08:32:13.333Z] INFO:  - Processed thread configs: 1
9:32:13 AM	Info	[2024-01-19T08:32:13.333Z] INFO:  - Processed threads: 1
9:32:13 AM	Info	[2024-01-19T08:32:13.334Z] INFO:  - Processed message configs: 0
9:32:13 AM	Info	[2024-01-19T08:32:13.335Z] INFO:  - Processed messages: 0
9:32:13 AM	Info	[2024-01-19T08:32:13.336Z] INFO:  - Processed attachment configs: 0
9:32:13 AM	Info	[2024-01-19T08:32:13.337Z] INFO:  - Processed attachments: 0
9:32:13 AM	Info	[2024-01-19T08:32:13.337Z] INFO:  - Executed actions: 2
9:32:13 AM	Info	[2024-01-19T08:32:13.338Z] INFO:  - Result status: ok
9:32:13 AM	Notice	Execution completed

**Comment by ahochsteger** [comment]
@ptorner the problem in your case is, that there's a message action (`message.forward`) within a thread action config. In the context of a thread there is not yet a message being processed thus no message (or attachment) action can be executed in a thread context.
Have a look at the [action documentation](https://ahochsteger.github.io/gmail-processor/docs/reference/actions) which documents which actions can be executed in which context.
You can also use the [Gmail Processor Playground](https://ahochsteger.github.io/gmail-processor/playground) to create and validate your JSON configuration.
