### ISSUE TITLE
Not working for large attachments (links of GDrive) in email

### ISSUE THREAD

**Issue by kind50ul** [ahochsteger/gmail-processor#45]
I tried the script on emails with attachments of size above 25MB (gdrive links). But the script didn't work on the shared links but was able to download the other normal attachments in the same email. I already tried using 'has:drive' in the config file but it didn't work for me, is there any solution to this?

**Comment by ahochsteger** [comment]
@sactyr  Gmail2Gdrive did not support GDrive attachments.
Please [migrate](https://ahochsteger.github.io/gmail-processor/docs/migrating) to it's successor [Gmail Processor](https://ahochsteger.github.io/gmail-processor/) which is much more powerful and added support for this feature in release [v2.4.0](https://github.com/ahochsteger/gmail-processor/releases/tag/2.4.0).
Have a look at [this FAQ entry](https://ahochsteger.github.io/gmail-processor/docs/faqs#how-do-i-store-gdrive-attachments-in-emails) that shows how to do it.
