### ISSUE TITLE
How do I override the global thread match query?

### ISSUE THREAD

**Issue by NiceGuyIT** [ahochsteger/gmail-processor#454]
### Describe the bug

I'm, trying to save attachments to Google Drive and started with the [Store Attachment][1] example. That example has a `global.thread.match.query` object that I adjusted to match the exact emails I want to process. Here's the query.

```javascript
global: {
  thread: {
    match: {
      query:
        'has:attachment -in:trash -in:drafts -in:spam label:resume has:attachment subject:["Resume Submitted"]'
    },
  },
}
```

Nothing was matched and I found this in the logs. For some reason it's appending `has:attachment -in:trash -in:drafts -in:spam newer_than:1d` to the query I'm providing and the `newer_than:1d` is the problem.

```text
2024-12-11T13:45:45.178Z INFO GMail search query: has:attachment -in:trash -in:drafts -in:spam label:resume has:attachment subject:["Resume Submitted"] has:attachment -in:trash -in:drafts -in:spam newer_than:1d
```

The [Config Schema][2] states the following for the `GlobalConfig.ThreadConfig.ThreadMatchConfig.query`. All examples use a `global.thread.match.query` object and this wording indicates it will be added to the "global query". Isn't `global.thread.match.query` the global query?

> The GMail search query additional to the global query to find threads to be processed. See [Search operators you can use with Gmail](https://support.google.com/mail/answer/7190?hl=en) for more information.

### To Reproduce

1. Run the [Store Attachment][1] verbatim.
2. View the logs. An extra argument is not logged.
3. Since I am not the sender, comment out the `threads.match.query` and run it again.
4. View the logs. The resulting query has `as:attachment -in:trash -in:drafts -in:spam newer_than:1d` appended to it.

### Expected behavior

The [Store Attachment][1] has the best explanation of how `threads`, `messages` and `attachments` work. The paragraph below states that if the `messages` section does not have a match section, all messages will be processed. I removed the `threads.match` section thinking it will return all threads that match the global query. Sadly, it took a while to discover that's not how it works.
> Since the messages section does not have any additional matcher, all messages in the thread will be processed.Since the messages section does not have any additional matcher, all messages in the thread will be processed.

### Logs / Screenshots

If applicable, add logs or screenshots to help explain your problem.

### Additional context

Affected version of gmail-processor: 30 (production version)

This is a documentation issue. Please elaborate on how threads work and why a default match is appended if `threads.match` is not provided. This was very confusing. Knowing the above, it's easy to a date range (i.e. `newer_than:3m`) to the `threads.match.query` to prevent the default from being appended.

[1]: https://ahochsteger.github.io/gmail-processor/docs/examples/basics/simple
[2]: https://ahochsteger.github.io/gmail-processor/docs/reference/config-schema/

**Comment by ahochsteger** [comment]
@NiceGuyIT thanks for pointing that out, this is indeed not very intuitive and I'll have a look to make that clear in the documentation!

If you do not set a global thread query than a [built-in global thread query](https://github.com/ahochsteger/gmail-processor/blob/086040675dea3d5cdc14108f945e98349b09a89b/src/lib/config/ThreadMatchConfig.ts#L6-L9) is used by default: `has:attachment -in:trash -in:drafts -in:spam newer_than:1d`
This guards from accidently processing all emails in your GMail account.

Therefore I'd always recommend setting at least a minimum default like for example `-in:trash -in:drafts -in:spam` and additionally to limit it to threads within a desired time range using `after` or `newer_than`.

**Comment by NiceGuyIT** [comment]
@ahochsteger To elaborate on my use case, I'm using this to save attachments to Google Drive and save the sender's email and drive link to a Google Sheet. I can then copy this to another spreadsheet to manage the attachments.

With that said, I'm using it to process historical emails, specifically all emails with a given label. After moving (labeling?) all emails to a folder/label, I make sure the global query matches what I'm looking for by pasting it into the Gmail search. If I don't get what I'm looking for, I adjust. In that regard, I want to process all emails in the global query because that's what I copy/paste and verify in Gmail. Having to add or manage another search criteria for the thread query is an extra but necessary step.

I'm beginning to see the power this App Script. Thank you!
