### ISSUE TITLE
Case sensitive file extension for attachments

### ISSUE THREAD

**Issue by sactyr** [ahochsteger/gmail-processor#51]
First, thank you for the great script  - it works beautifully.

I tried editing the rules for file extension so that it's not case sensitive e.g. it accepts both .pdf and .PDF

"filenameFromRegexp": ".*\.pdf$" to "filenameFromRegexp": ".*\(?i).pdf$"

and I am getting the following error in the execution log:
SyntaxError: Invalid regular expression: /.*(?i).pdf$/: Invalid group

For the life of me I can't figure out what's the correct syntax, anyone with better regex skills? Thanks

**Comment by zzzZZZzzz9** [comment]
`"filenameFromRegexp": ".*\.pdf$|.*\.PDF$"`

**Comment by ahochsteger** [comment]
@sactyr  Gmail2Gdrive did not support passing regex modifier flags in the config.
Please [migrate](https://ahochsteger.github.io/gmail-processor/docs/migrating) to it's successor [Gmail Processor](https://ahochsteger.github.io/gmail-processor/) which added support for this feature in release [v2.4.0](https://github.com/ahochsteger/gmail-processor/releases/tag/2.4.0).
In your case the relevant matching config would look like this:
```json
"match": {
  "name": "(?i)\\.pdf$"
}
```
Also note, that Gmail Processor provides a lot more features like capturing multiple parts of the string and using them to construct the file location in GDrive.
