### ISSUE TITLE
Use subject substring for attachment filename

### ISSUE THREAD

**Issue by ahochsteger** [ahochsteger/gmail-processor#6]
Usage example (by @CgKortz):
- Attachment original name is: `Image-1.jpg` 
- Subject of email is: `UDisc iOS Scorecard - McClain Park (Default Layout - 05-28-2016 08:35 AM)`

I would like the attachment to be renamed: `McClain Park 05-28-2016 08:35 AM`
I would think removing the `(Default Layout -` might be harder but to remove the `UDisc iOS Scorecard -` should be easy like remove the first 22 characters of the subject before the rename. I googled some and I could not find anything but I also have never scripted so ..... any help would be greatly appreciated.

**Comment by ahochsteger** [comment]
@CgKortz, I guess something like this would be flexible enough to satisfy your requirements:

    { // Replace all files with the variable 'filenameTo' string.
        "filter": "(from:example3a@example.com OR from:example3b@example.com)",
        "folder": "Examples/example3ab",
        "subjectRegex": "UDisc iOS Scorecard - ([^())]+) \(Default Layout - ([APM0-9: -]{19})\)", // Provides the matching regex groups as $1, $2, ... for substitution in filenameTo
        "filenameFrom": "Image-1.jpg",
        "filenameTo": "'$1$2''",
        "archive": true
    }

Please tell me, if that's what you were looking for.
I'd try to implement it since it would indeed make it much more flexible to use!

**Comment by CgKortz** [comment]
That looks like what I am looking for.

**Comment by ahochsteger** [comment]
@CgKortz, may you try, if the file [Code.gs.txt](https://github.com/ahochsteger/gmail2gdrive/files/301343/Code.gs.txt) does what you expect?

I've tested it with the following configuration (please adjust to your usage):

    { // Replace all files with the variable 'filenameTo' string using regex match groups from subjectRegex.
        "filter": "from:example@example.com", 
        "folder": "Test-Folder", 
        "subjectRegex": "Prefix - (.*) - Suffix", // Provides the matching regex groups as $1, $2, ... for substitution in filenameTo
        "filenameFrom": "testfile.txt", 
        "filenameTo": "'$1 'yyyy-MM-dd",
        "archive": true 
    },

The test email had the subject `Prefix - Test E-Mail 1 - Suffix` and an attachment with the filename `testfile.txt`.

Please tell me, if this works for you so I can integrate that change.

**Comment by CgKortz** [comment]
This dose not seem to work. I have tried with my own Regex and I used your example as well. I just get the attachment as the original attachment name.

**Comment by CgKortz** [comment]
Log File
16-06-07 13:49:12:407 CDT] INFO: Starting mail attachment processing.
[16-06-07 13:49:12:530 CDT] INFO: Processing rule: subject:UDisc iOS Scorecard -label:processed newer_than:1m
[16-06-07 13:49:12:531 CDT] INFO:     Processing thread: UDisc iOS Scorecard - Prince Solms (Default Layout - 06-07-2016 11:14 AM) (runtime: 0.125s/280s)
[16-06-07 13:49:12:657 CDT] INFO:       Processing message: UDisc iOS Scorecard - Prince Solms (Default Layout - 06-07-2016 11:14 AM) (1552bcc0c8726ae5)
[16-06-07 13:49:12:659 CDT] INFO:         Processing attachment: Image-1.jpg
[16-06-07 13:49:14:624 CDT] INFO:           constructNewFilename('UDisc iOS Scorecard - ([^())]+) (.* - ([APM0-9: -]{19}))', ''$1$2''')
[16-06-07 13:49:14:625 CDT] Exception: Invalid argument: 'Prince Solms(Default Layout - 06-07-2016 11:14 AM'')

**Comment by fairyfeller** [comment]
Is there any chance to overwrite current file ? For example - i receive stock info everyday with file named "Company stock 24-05-2017.xls".
i created rule for renaming it to stock.xls, but every day i have new duplicates with same name.

**Comment by MikeL63** [comment]
Thank you so much for this project.  Your work is greatly appreciated.  Has any progress been made to rename the file uploaded to Google Drive as the subject line?  I would also like to place the file in a folder that is named by the content of the message body.  I am using this with a form in Acrobat.  The user submits the form and the subject line and body of the email is generated based off of form content.  The form is submitted by email to a gmail account.  Any help would be very much appreciated as I am pretty new to scripting.

**Comment by ahochsteger** [comment]
I guess to better handle functionality like that and get more flexibility for the future it is necessary to redo the logic.
Therefore I'd like to get some feedback about how the configuration could be enhanced to be more flexible.

This configuration draft shows how more flexible replacement parameters for the location of the attachments to be stored may be supported:

**Example configuration (DRAFT):**

```javascript
{
    "filter": "has:attachment from:example4@example.com",
    "match": {
        "subject": "Prefix - (.*) - Suffix",
        "from": "(.+)@example.com"
    }
    "attachments": [
        {
            "match": "Image-([0-9]+)\.jpg",
            "location": "Folder1/Subfolder1/${match.subject.1}/${email.subject} - ${match.att.1}.jpg"
            // example: subject="Prefix - Test - Suffix", filename="Image-3.jpg" =>
            //   location="Folder1/Subfolder1/Test/Prefix - Test - Suffix - 3.jpg
        },
        {
            "match": ".+\..+", // means *.* or <att.basename>.<att.ext>
            "location": "Folder2/Subfolder2/${att.basename}-${date:yyyy-MM-dd}.${att.ext}"
            // example: subject="Prefix - Test - Suffix", filename="file.txt" =>
            //   location="Folder2/Subfolder2/Test/Prefix - Test - Suffix - 3.jpg
        }
    ],
},
```

**Substitution parameters (DRAFT):**

* Emails:
  * **${email.subject}:** Subject
  * **${email.from}:** Sender email
  * **${email.date:<SimpleDateFormat>}:** Date and time
    * e.g. ```${date:yyyy-MM-dd_HH-mm-ss}```
    * For all supported format letters see <https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html>
* Attachments
  * **${att.filename}:** Attachment filename
  * **${att.basename}:** Attachment file basename without extension
  * **${att.ext}:** Attachment file extension
* Regular expression matching groups:
  * **${match.subject.[1-9]}:** Matching subject string
  * **${match.from.[1-9]}:** Matching from string
  * **${match.att.[1-9]}:** Matching attachment filename string
  * The parenthesis "()" define the possible match groups counted from left to right.
  * For more information about using regular expressions see <https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/RegExp>

 Let me know if this would suit your needs :-).

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides the functionality mentioned above. 
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information
