### ISSUE TITLE
issues with filenameFromRegexp

### ISSUE THREAD

**Issue by costasfait** [ahochsteger/gmail-processor#87]
I am trying to select specific attachments with the filenameFromRegexp and place the sting below, which is not working though

"filenameFromRegexp": "/.*(?:aword|bword).*\.pdf/gi"

when testing with a regexp tester it works, though in the scrip is not working. it seems that the flags are not supported!

**Comment by ahochsteger** [comment]
@costasfait Gmail2Gdrive did not support passing regex modifier flags in the config.
Please [migrate](http://localhost:3000/gmail-processor/docs/migrating) to it's successor [Gmail Processor](https://ahochsteger.github.io/gmail-processor/) which added support for this feature in release [v2.4.0](https://github.com/ahochsteger/gmail-processor/releases/tag/2.4.0).
In your case the relevant matching config would look like this:
```json
"match": {
  "name": "(?i)(aword|bword)\\.pdf/gi"
}
```
Also note, that Gmail Processor provides a lot more features like capturing multiple parts of the string and using them to construct the file location in GDrive.
