### ISSUE TITLE
Examples page throws 404

### ISSUE THREAD

**Issue by plattze** [ahochsteger/gmail-processor#89]
New user here and following:  https://github.com/ahochsteger/gmail-processor#configuration-reference

Trying to follow the deployment guide and build a basic script to save certain emails to Google Drive.

Under Configuration References, it shows:  Have a look at the [examples](https://github.com/ahochsteger/gmail2gdrive/tree/v2/src/gas/examples) to see different usage scenarios.

However, this link throws a 404.  

PS. Is there a basic bootstrap config example to save all emails attachments from a specific sender into a specified folder?

**Comment by ahochsteger** [comment]
Welcome @plattze,
thanks for reporting, the link works now with v2.0.0 just released.
