### ISSUE TITLE
Stable release is not found when adding library.

### ISSUE THREAD

**Issue by mgslone** [ahochsteger/gmail-processor#96]
I used the script ID provided in the readme: `1Qvk0v7ggfW-TJ84dlYPlDzJG8y-Dif-j9kdA1aWv4wzxE_IOkeV2juLB`

It gives me an error `Unable to look up library. Check the ID and access permissions and try again.`

<img width="499" alt="Screenshot 2023-08-23 at 10 26 21 AM" src="https://github.com/ahochsteger/gmail-processor/assets/86614152/23485cda-f187-408c-9574-172209af8548">

Note: The beta release ID works.

**Comment by ahochsteger** [comment]
@mgslone thanks for reporting, the library sharing has been fixed and it should work now.
Please try again and let me know if it works for you.
Andreas
