### ISSUE TITLE
message.storePDF and thread.storePDF fail

### ISSUE THREAD

**Issue by plattze** [ahochsteger/gmail-processor#98]
I am trying to take an email without an attachment, and turn it into a PDF and store it somewhere.  Version 124.  To reproduce, I updated e2eTest01.js to perform this action (message.storePDF then thrad.storePDF) and both failed:

```
11:09:45 PM	Info	[2023-08-26T13:09:45.693Z] INFO: Executing action 'global.sheetLog' with args: {"message":"A sheetLog message for the matched thread.","level":"info"}
11:09:45 PM	Info	[2023-08-26T13:09:45.694Z] INFO: Logsheet: A sheetLog message for the matched thread.
11:09:45 PM	Info	[2023-08-26T13:09:45.698Z] DEBUG: Appending to logSheet: ["[GmailProcessor-Test] Test with a single attachments","2023-08-26 23:05:31","18a31f320d964d8f","https://mail.google.com/mail/u/0/#inbox/18a31f320d964d8f","","","","A sheetLog message for the matched thread."]
11:09:45 PM	Info	[2023-08-26T13:09:45.907Z] INFO: Action result: {"ok":true}
11:09:45 PM	Info	[2023-08-26T13:09:45.909Z] INFO: Executing action 'thread.storePDF' with args: {"folder":"/GmailProcessor-Tests/${message.date:format:yyyyMMdd} - ${attachment.name}","description":"PDF of test ${message.subject}","skipHeader":"true"}
11:09:45 PM	Info	[2023-08-26T13:09:45.910Z] DEBUG: Calling method 'storePDF' ...
11:09:45 PM	Info	[2023-08-26T13:09:45.913Z] INFO: Generating HTML code of thread '[GmailProcessor-Test] Test with a single attachments'
11:09:45 PM	Info	[2023-08-26T13:09:45.918Z] ERROR: Action thread.storePDF caused an error: {}
11:09:45 PM	Info	[2023-08-26T13:09:45.919Z] INFO: Action result: {"ok":false,"error":{}}
11:09:45 PM	Info	[2023-08-26T13:09:45.921Z] INFO: Processing of thread id 18a31f320d964d8f finished.
```

```
const e2eTest01ConfigV2 = {
  description: "End-to-end (E2E) test configuration",
  settings: {
    logSheetLocation:
      "/GmailProcessor-Tests/logsheet-${date.now:format:yyyy-MM}",
    maxBatchSize: 10,
    maxRuntime: 280,
    sleepTimeThreads: 100,
    sleepTimeMessages: 0,
    sleepTimeAttachments: 0,
    timezone: "UTC",
  },
  global: {
    thread: {
      match: {
        query: "has:attachment -in:trash -in:drafts -in:spam after:2023-06-19",
        maxMessageCount: -1,
        minMessageCount: 1,
      },
      actions: [],
    },
  },
  threads: [
    {
      actions: [
        {
          name: "global.log",
          args: {
            message: "A log message for the matched thread.",
            level: "info",
          },
        },
        {
          name: "global.sheetLog",
          args: {
            message: "A sheetLog message for the matched thread.",
            level: "info",
          },
        },
        {
          name: "thread.storePDF",
          args: {
            folder: "/GmailProcessor-Tests/${message.date:format:yyyyMMdd} - ${attachment.name}",
            description: "PDF of test ${message.subject}",
            skipHeader: "true"
          },
        },
      ],
      match: {
        query:
          "from:${user.email} to:${user.email} subject:'GmailProcessor-Test'",
      },
      attachments: [
        {
          match: {
            name: "^(?<basename>.+).png$",
          },
          actions: [
            {
              name: "attachment.store",
              args: {
                location:
                  "/GmailProcessor-Tests/v2/e2e01/${attachment.name.match.basename}-stored.png",
              },
            },
            {
              name: "global.log",
              args: {
                message: "A log message for the matched attachment.",
                level: "info",
              },
            },
            {
              name: "global.sheetLog",
              args: {
                message: "A sheetLog message for the matched attachment.",
                level: "info",
              },
            },
          ],
        },
      ],
    },
  ],
}

function e2eTest01Run() {
  GmailProcessor.run(e2eTest01ConfigV2, "safe-mode")
}
```

**Comment by plattze** [comment]
message.forward fails too:

6:46:18 PM	Info	[2023-08-28T08:46:18.713Z] INFO: Executing action 'message.forward' with args: {"to":"redacted@redacted.com"}
6:46:18 PM	Info	[2023-08-28T08:46:18.714Z] DEBUG: Calling method 'forward' ...
6:46:18 PM	Info	[2023-08-28T08:46:18.728Z] ERROR: Action message.forward caused an error: {}
6:46:18 PM	Info	[2023-08-28T08:46:18.729Z] INFO: Action result: {"ok":false,"error":{}}
6:46:18 PM	Info	[2023-08-28T08:46:18.731Z] INFO: Processing of thread id 18a3b4ee6bb9eed7 finished.

```

  global: {
    thread: {
      match: {
        query: "-in:trash -in:drafts -in:spam newer_than:1d", /* has:attachment */
        maxMessageCount: -1,
        minMessageCount: 1,
      },
      actions: [
        {
          name: "message.forward",
          args: {
            to: "redacted@redacted.com"
          },
        },
      ],
    },
  },
```

**Comment by plattze** [comment]
Project OAuth Scopes 

See your primary Google Account email address	https://www.googleapis.com/auth/userinfo.email
Read, compose, send, and permanently delete all your email from Gmail	https://mail.google.com/
See, edit, create, and delete all of your Google Drive files	https://www.googleapis.com/auth/drive
Connect to an external service	https://www.googleapis.com/auth/script.external_request
Send email as you	https://www.googleapis.com/auth/script.send_mail
See, edit, create, and delete all your Google Sheets spreadsheets	https://www.googleapis.com/auth/spreadsheets

**Comment by ahochsteger** [comment]
@plattze v2.0.5 fixes a bug concerning action error handling.
It would be great, if you could give it a try.
If it still fails, at least it should tell now why in the logs.

**Comment by ahochsteger** [comment]
@plattze yes, it's a pitty, that the version selector does not show the version description.
The release version `2.0.5` corresponds to version `7` in Google Apps Script.
You will have to switch to the stable version of the library using ID `1Qvk0v7ggfW-TJ84dlYPlDzJG8y-Dif-j9kdA1aWv4wzxE_IOkeV2juLB` to get stable releases.
The one you're currently using just contains unstable development snapshots, meant for testing pre-releases.
Have a look at the README for more information:
<https://github.com/ahochsteger/gmail-processor#use-a-library-reference-recommended>

This URL can be used to verify the release version of a Google Apps Script Library (in this case version 7 which contains release version 2.0.5):
https://script.google.com/macros/library/d/1Qvk0v7ggfW-TJ84dlYPlDzJG8y-Dif-j9kdA1aWv4wzxE_IOkeV2juLB/7

**Comment by ahochsteger** [comment]
Assuming the issue is closed now, since there have been multiple bug fixes concerning action handling up until the current version [v2.3.0](https://github.com/ahochsteger/gmail-processor/releases/tag/2.3.0).
Also note, that the release notes now always contain the corresponding Google Apps Script library version number.
